#!/usr/bin/env python3
"""
Generate a simple Go stone as a cylinder with hemispherical caps.
Much simpler geometry - should avoid all the topology issues.
"""

import math
import sys

def generate_stone_simple(radius=0.5, height=0.243, segments=48):
    """
    Generate a simple stone: cylinder with hemispherical top/bottom.

    Total height = height (cylinder) + 2 * cap_height
    For go stones, we want total ~0.486 * diameter
    So if radius=0.5, total should be ~0.486
    Cylinder height = 0.243, each cap = 0.1215
    """
    vertices = []
    normals = []
    uvs = []
    faces = []

    cap_height = height / 2.0  # Each hemisphere cap

    # Simple approach: just make a flattened sphere
    # No cylinder part, just a pure ellipsoid

    stacks = 16

    # Top vertex
    vertices.append((0, radius * 0.486, 0))
    normals.append((0, 1, 0))
    uvs.append((0.5, 0.5))

    # Generate latitude rings
    for i in range(1, stacks):
        lat = math.pi * i / stacks
        y = math.cos(lat) * radius * 0.486
        ring_radius = math.sin(lat) * radius

        for j in range(segments):
            lon = 2 * math.pi * j / segments
            x = math.cos(lon) * ring_radius
            z = math.sin(lon) * ring_radius

            vertices.append((x, y, z))

            # Normal for ellipsoid
            nx = x
            ny = y / (0.486 * 0.486)
            nz = z
            length = math.sqrt(nx*nx + ny*ny + nz*nz)
            normals.append((nx/length, ny/length, nz/length))

            # Planar UV
            u = 0.5 + x / (radius * 2)
            v = 0.5 + z / (radius * 2)
            uvs.append((u, v))

    # Bottom vertex
    vertices.append((0, -radius * 0.486, 0))
    normals.append((0, -1, 0))
    uvs.append((0.5, 0.5))

    # Top cap faces
    for i in range(segments):
        v1 = 0
        v2 = 1 + i
        v3 = 1 + ((i + 1) % segments)
        faces.append((v1, v2, v3))

    # Middle faces
    for i in range(stacks - 2):
        for j in range(segments):
            # Quad between rings
            curr = 1 + i * segments + j
            next_seg = 1 + i * segments + ((j + 1) % segments)
            next_ring = 1 + (i + 1) * segments + j
            next_both = 1 + (i + 1) * segments + ((j + 1) % segments)

            faces.append((curr, next_seg, next_ring))
            faces.append((next_seg, next_both, next_ring))

    # Bottom cap
    bottom_idx = len(vertices) - 1
    last_ring_start = 1 + (stacks - 2) * segments

    for i in range(segments):
        v1 = bottom_idx
        v2 = last_ring_start + ((i + 1) % segments)
        v3 = last_ring_start + i
        faces.append((v1, v2, v3))

    print(f"Generated {len(vertices)} vertices, {len(faces)} faces")
    return vertices, normals, uvs, faces


def write_obj(filename, vertices, normals, uvs, faces):
    """Write to Wavefront OBJ format - simpler than COLLADA"""
    with open(filename, 'w') as f:
        f.write("# Go Stone Model\n")
        f.write("# Generated by generate_stone_model.py\n\n")

        # Vertices
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n")

        # Texture coordinates
        for uv in uvs:
            f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
        f.write("\n")

        # Normals
        for n in normals:
            f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
        f.write("\n")

        # Faces (OBJ indices start at 1)
        for face in faces:
            # Format: f v1/vt1/vn1 v2/vt2/vn2 v3/vt3/vn3
            f.write(f"f {face[0]+1}/{face[0]+1}/{face[0]+1} ")
            f.write(f"{face[1]+1}/{face[1]+1}/{face[1]+1} ")
            f.write(f"{face[2]+1}/{face[2]+1}/{face[2]+1}\n")


if __name__ == '__main__':
    output_file = 'stone.obj'
    if len(sys.argv) > 1:
        output_file = sys.argv[1]

    print("Generating simple Go stone (ellipsoid)...")
    vertices, normals, uvs, faces = generate_stone_simple(
        radius=0.5,
        height=0.243,
        segments=48
    )

    print(f"Writing to {output_file}...")
    write_obj(output_file, vertices, normals, uvs, faces)

    print(f"Done! Model saved to {output_file}")
    print("\nThis is a simple ellipsoid with planar UV mapping.")
    print("Should work with SceneKit using SCNScene(named: ...)")
